### ISSUE TITLE
Put files in solution

### ISSUE THREAD

**Issue by laurentiustamate94** [microsoft-dx/slack-history-viewer#1]
Create a solution and a .NET Core project for the files in [restore-from-local branch](https://github.com/microsoft-dx/slack-history-viewer/tree/restore-from-local)

**Comment by laurentiustamate94** [comment]
You can create a .NET Standard library and reference it in a .NET Core console app.

**Comment by laurentiustamate94** [comment]
#2

**Comment by laurentiustamate94** [comment]
#2

**Comment by sanzivoicu** [comment]
fixed
